src/authorization/urls.py
from django.urls import path
from . import views

app_name = 'authorization'

urlpatterns = [
    path('login/', views.Login.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

src/gallery/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('images/', include('images.urls')),
    path('accounts/', include('authorization.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/images/urls.py
from django.urls import path
from . import views

app_name = 'images'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddImageView.as_view(), name='add-image'),
    path('<pk>/like/', views.LikeView.as_view(), name='like'),
    path('<pk>/', views.ImageView.as_view(), name='image'),
    path('<pk>/add-comment/', views.AddCommentView.as_view(), name='add-comment'),
    path('<pk>/get-comments/', views.GetCommentsView.as_view(), name='get-comments'),
]

src/authorization/models.py
from django.db import models

# Create your models here.

src/images/models.py
from django.contrib.auth.models import User
from django.db import models


class Image(models.Model):
    image = models.ImageField(upload_to='images/')
    signature = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, blank=True, related_name='likes')
    comments = models.ManyToManyField(User, blank=True, related_name='comments', through='Comment')


class Comment(models.Model):
    text = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ForeignKey(Image, on_delete=models.CASCADE)

src/authorization/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)

    def save(self):
        User.objects.create_user(username=self['username'].value(), password=self['password'].value())

src/images/forms.py
from django import forms

from .models import Comment, Image


class ImageForm(forms.Form):
    image = forms.ImageField(required=True)
    signature = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Описание к фото'}))


class CommentForm(forms.Form):
    text = forms.CharField(max_length=200)

    def save(self, user, image_id):
        Comment.objects.create(text=self['text'].value(), author=user, image=Image.objects.get(pk=image_id))

src/authorization/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import FormView

from .forms import UserForm


class Login(LoginView):
    pass


class Logout(LogoutView):
    pass


class RegisterView(FormView):
    template_name = 'registration/register.html'
    form_class = UserForm
    success_url = reverse_lazy('authorization:login')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('images:index')
        return super().get(request, *args, **kwargs)

src/images/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, RedirectView, DetailView, FormView

from .forms import ImageForm, CommentForm
from .models import Image, Comment


class IndexView(ListView):
    model = Image
    context_object_name = 'images'
    extra_context = {'form': ImageForm()}
    template_name = 'images/index.html'
    paginate_by = 3
    ordering = '-id'


class AddImageView(LoginRequiredMixin, CreateView):
    login_url = 'authorization:login'
    model = Image
    fields = ['image', 'signature']
    success_url = reverse_lazy('images:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class LikeView(LoginRequiredMixin, RedirectView):
    login_url = 'authorization:login'

    def get(self, *args, **kwargs):
        image = Image.objects.get(id=self.kwargs['pk'])

        if image.likes.filter(id=self.request.user.id).exists():
            image.likes.remove(self.request.user)
        else:
            image.likes.add(self.request.user)

        return JsonResponse({'likes': image.likes.count()})


class ImageView(DetailView):
    template_name = 'images/comments.html'
    model = Image
    context_object_name = 'image'

    def get_context_data(self, **kwargs):
        kwargs['form'] = CommentForm
        return super().get_context_data(**kwargs)


class AddCommentView(LoginRequiredMixin, FormView):
    login_url = 'authorization:login'
    form_class = CommentForm

    def form_valid(self, form):
        form.save(self.request.user, self.kwargs['pk'])
        return JsonResponse({'username': self.request.user.username})


class GetCommentsView(RedirectView):
    def get(self, *args, **kwargs):
        comments = Comment.objects.filter(image=Image.objects.get(pk=kwargs['pk']))
        data = {}

        for comment in comments:
            data[comment.id] = {}
            data[comment.id]['author'] = comment.author.username
            data[comment.id]['text'] = comment.text

        return JsonResponse({'comments': data})

src/images/templates/images/comments.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Comments</title>
    <link rel="stylesheet" type="text/css" href="{% static 'images/style.css' %}">
</head>
<body>
    <img src="{{ image.image.url }}" class="comments-image"><br><br>

    <div class="comments-block"></div><br>

    {% if user.is_authenticated %}
        <form method="post" class="add-comment" name="{{ image.id }}" action="{% url 'images:add-comment' image.id %}">
            {% csrf_token %}
            {{ user.username }}: {{ form.text }}
            <button type="submit">Отправить</button>
        </form><br>
    {% endif %}

    <a href="{% url 'images:index' %}">Назад</a>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'images/scripts/comments.js' %}"></script>
</body>
</html>

src/images/templates/images/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Gallery</title>
    <link rel="stylesheet" type="text/css" href="{% static 'images/style.css' %}">
</head>
<body>
    {% if user.is_authenticated %}
        <form method="post" enctype="multipart/form-data" action="{% url 'images:add-image' %}">
            {% csrf_token %}
            {{ form.image }}<br><br>
            {{ form.signature }}<br><br>
            <input type="submit" value="Добавить"><br><br>
        </form>
    {% else %}
        <a href="{% url 'authorization:login' %}">Авторизоваться</a><br><br>
    {% endif %}

    {% if user.is_authenticated %}
        <b>{{ user.username }}</b> (<a href="/accounts/logout/">выйти</a>)<br><br>
    {% endif %}

    <div class="wrapper">
    {% for image in images %}
        <div>
            <a href="{{image.image.url}}" target="_blank"><img src="{{ image.image.url }}" class="an-image"></a><br>
            <b>{{ image.signature }}</b><br>
            Автор: <b>{{ image.user.username }}</b><br>
            {% if user.is_authenticated %}
                {% if user in image.likes.all %}
                    <a name="{{ image.id }}" class="like"><img src="{% static 'images/icons/like_set.png' %}"></a>
                {% else %}
                    <a name="{{ image.id }}" class="like"><img src="{% static 'images/icons/like_unset.png' %}"></a>
                {% endif %}
            {% else %}
                <img src="{% static 'images/icons/like_unset.png' %}">
            {% endif %}
            <span class="like_counter">{{ image.likes.count }}</span> | <a href="{% url 'images:image' image.id %}" name="{{ image.id }}" class="comments"><img src="{% static 'images/icons/comment.png' %}"></a> {{ image.comments.count }}
        </div>
    {% endfor %}
    </div><br><br>

    <div class="paginator">
        {% if page_obj.has_previous %}
            <a href="?page=1">|<<|</a>
            <a href="?page={{ page_obj.previous_page_number }}"><|</a>
        {% endif %}

        Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">|></a>
            <a href="?page={{ page_obj.paginator.num_pages }}">|>>|</a>
        {% endif %}
    </div>

            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script src="{% static 'images/scripts/like.js' %}"></script>
</body>
</html>